services:
  php:
    user: "1000:1000"
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - ./:/var/www/html
      - ./data:/var/www/html/data
    working_dir: /var/www/html
    expose:
      - 9000
    env_file:
      - .env

  nginx:
    image: nginx:stable
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
